server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.154.180:8806/cloudDB01?serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5             #数据库连接池的最小维持连接数
      initial-size: 5         #初始化连接数
      max-total: 5            #最大连接数
      max-wait-millis: 200    #等待连接获取的最大超时时间